@startuml arch

package "v1" {

database "PostgreSQL" as db
component "Blazor Server" as server {
    card "SignalR Hub" as signalr
    card "Auth" as auth
    card "Message Queue" as mq
    card "UI Controllers" as ui
}

server - db
}
@enduml
@startuml archv2
package "v2" {

database "PostgreSQL" as db
component "Blazor Server" as server {
    card "SignalR Hub" as signalr
    card "Auth API" as auth
    card "Message Queue" as mq
}
component "React Frontend" as frontend

server - db
}
@enduml